# Generated by Django 4.2.13 on 2026-06-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100, verbose_name='Time da casa')),
                ('home_flag', models.CharField(max_length=20, verbose_name='Bandeira da casa')),
                ('away_team', models.CharField(max_length=100, verbose_name='Time visitante')),
                ('away_flag', models.CharField(max_length=20, verbose_name='Bandeira visitante')),
                ('match_datetime', models.DateTimeField(verbose_name='Data e hora da partida')),
                ('home_score', models.IntegerField(blank=True, null=True, verbose_name='Gols da casa')),
                ('away_score', models.IntegerField(blank=True, null=True, verbose_name='Gols visitante')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Finalizada')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['match_datetime'],
            },
        ),
    ]
