// Código ISO 3166-1 alpha-2 de cada país
// A bandeira é renderizada via <img src={flagUrl(code)} /> — funciona em todos os sistemas
export const flagUrl = (code) =>
  `https://flagcdn.com/w40/${code.toLowerCase()}.png`

export const COUNTRIES = [
  { name: "África do Sul",   code: "za" },
  { name: "Albânia",         code: "al" },
  { name: "Alemanha",        code: "de" },
  { name: "Arábia Saudita",  code: "sa" },
  { name: "Argentina",       code: "ar" },
  { name: "Austrália",       code: "au" },
  { name: "Bélgica",         code: "be" },
  { name: "Brasil",          code: "br" },
  { name: "Canadá",          code: "ca" },
  { name: "Chile",           code: "cl" },
  { name: "Colômbia",        code: "co" },
  { name: "Coreia do Sul",   code: "kr" },
  { name: "Costa Rica",      code: "cr" },
  { name: "Croácia",         code: "hr" },
  { name: "Dinamarca",       code: "dk" },
  { name: "Egito",           code: "eg" },
  { name: "Equador",         code: "ec" },
  { name: "Eslováquia",      code: "sk" },
  { name: "Eslovênia",       code: "si" },
  { name: "Espanha",         code: "es" },
  { name: "Estados Unidos",  code: "us" },
  { name: "França",          code: "fr" },
  { name: "Gana",            code: "gh" },
  { name: "Guatemala",       code: "gt" },
  { name: "Holanda",         code: "nl" },
  { name: "Honduras",        code: "hn" },
  { name: "Hungria",         code: "hu" },
  { name: "Inglaterra",      code: "gb-eng" },
  { name: "Irã",             code: "ir" },
  { name: "Irlanda",         code: "ie" },
  { name: "Japão",           code: "jp" },
  { name: "Marrocos",        code: "ma" },
  { name: "México",          code: "mx" },
  { name: "Nigéria",         code: "ng" },
  { name: "Noruega",         code: "no" },
  { name: "Panamá",          code: "pa" },
  { name: "Peru",            code: "pe" },
  { name: "Polônia",         code: "pl" },
  { name: "Portugal",        code: "pt" },
  { name: "Qatar",           code: "qa" },
  { name: "Romênia",         code: "ro" },
  { name: "Senegal",         code: "sn" },
  { name: "Sérvia",          code: "rs" },
  { name: "Suíça",           code: "ch" },
  { name: "Turquia",         code: "tr" },
  { name: "Ucrânia",         code: "ua" },
  { name: "Uruguai",         code: "uy" },
  { name: "Venezuela",       code: "ve" },
].sort((a, b) => a.name.localeCompare(b.name, "pt-BR"))
