export const COUNTRIES = [
  { name: "Argentina", flag: "🇦🇷" },
  { name: "Austrália", flag: "🇦🇺" },
  { name: "Bélgica", flag: "🇧🇪" },
  { name: "Brasil", flag: "🇧🇷" },
  { name: "Canadá", flag: "🇨🇦" },
  { name: "Chile", flag: "🇨🇱" },
  { name: "Colômbia", flag: "🇨🇴" },
  { name: "Costa Rica", flag: "🇨🇷" },
  { name: "Croácia", flag: "🇭🇷" },
  { name: "Dinamarca", flag: "🇩🇰" },
  { name: "Egito", flag: "🇪🇬" },
  { name: "Equador", flag: "🇪🇨" },
  { name: "Espanha", flag: "🇪🇸" },
  { name: "Estados Unidos", flag: "🇺🇸" },
  { name: "França", flag: "🇫🇷" },
  { name: "Alemanha", flag: "🇩🇪" },
  { name: "Gana", flag: "🇬🇭" },
  { name: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { name: "Holanda", flag: "🇳🇱" },
  { name: "Honduras", flag: "🇭🇳" },
  { name: "Hungria", flag: "🇭🇺" },
  { name: "Irã", flag: "🇮🇷" },
  { name: "Japão", flag: "🇯🇵" },
  { name: "Coreia do Sul", flag: "🇰🇷" },
  { name: "Marrocos", flag: "🇲🇦" },
  { name: "México", flag: "🇲🇽" },
  { name: "Nigéria", flag: "🇳🇬" },
  { name: "Noruega", flag: "🇳🇴" },
  { name: "Panamá", flag: "🇵🇦" },
  { name: "Peru", flag: "🇵🇪" },
  { name: "Polônia", flag: "🇵🇱" },
  { name: "Portugal", flag: "🇵🇹" },
  { name: "Qatar", flag: "🇶🇦" },
  { name: "Romênia", flag: "🇷🇴" },
  { name: "Arábia Saudita", flag: "🇸🇦" },
  { name: "Senegal", flag: "🇸🇳" },
  { name: "Sérvia", flag: "🇷🇸" },
  { name: "África do Sul", flag: "🇿🇦" },
  { name: "Suíça", flag: "🇨🇭" },
  { name: "Turquia", flag: "🇹🇷" },
  { name: "Ucrânia", flag: "🇺🇦" },
  { name: "Uruguai", flag: "🇺🇾" },
  { name: "Venezuela", flag: "🇻🇪" },
  { name: "Eslováquia", flag: "🇸🇰" },
  { name: "Eslovênia", flag: "🇸🇮" },
  { name: "Irlanda", flag: "🇮🇪" },
  { name: "Albânia", flag: "🇦🇱" },
  { name: "Guatemala", flag: "🇬🇹" },
]
